import type { Metadata } from "next";
import { Geist, Geist_Mono, Major_Mono_Display } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "../lib/lenis";

const silk = Major_Mono_Display({
  variable: "--font-silk",
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactLenis root>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${silk.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ReactLenis>
  );
}
